---
- name: Install stow
  become: yes
  ansible.builtin.package: 
    name: stow
  tags: [dotfiles, ohmyzsh, neovim, tmux]

- name: Clone .dotfiles repo
  ansible.builtin.git:
    repo: "git@github.com:xwilk/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    key_file: /home/piwilk/.ssh/id_rsa
  tags: [dotfiles, ohmyzsh, neovim, tmux]

