---
- name: Print params
  ansible.builtin.debug:
    msg: "{{ source_key }}, {{ dest_key }}, {{ user }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: Install ssh key public
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: Set authorized key took from file
  ansible.builtin.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"

- name: Install keychain
  become: yes
  ansible.builtin.package:
    name: keychain

- name: Start long-running ssh-agent with keychain
  ansible.builtin.shell: keychain id_rsa && . ~/.keychain/`uname -n`-sh -q

- name: Add keychain command to .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: keychain id_rsa && source ~/.keychain/`uname -n`-sh

