---
- name: install fzf
  become: yes
  ansible.builtin.package:
    name: fzf
  tags: [tmux]

- name: stow custom scripts from dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && stow bin
  tags: [tmux]

- name: install tmux
  become: yes
  ansible.builtin.package:
    name: tmux
  tags: [tmux]

- name: stow tmux config
  ansible.builtin.shell: cd $HOME/.dotfiles && stow tmux
  tags: [tmux]

- name: clone tpm
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
    key_file: /home/piwilk/.ssh/id_rsa
  tags: [tmux]

