---
- name: clone neovim repo
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ lookup('env', 'HOME') }}/build/neovim"
    depth: 1
  tags: [neovim]

- name: Install ninja
  become: yes
  ansible.builtin.package: 
    name: ninja-build 
  tags: [neovim]

- name: Install cmake 
  become: yes
  ansible.builtin.package: 
    name: cmake 
  tags: [neovim]

- name: make build neovim
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/build/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  tags: [neovim]

- name: make install neovim
  become: yes
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/build/neovim"
    target: install
  tags: [neovim]

- name: Install packer.nvim
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags: [neovim]

- name: remove configuration files
  ansible.builtin.file:
    name: ~/.config
    state: absent
  tags: [neovim]

- name: stow zsh config files
  ansible.builtin.shell: cd $HOME/.dotfiles && stow nvim
  tags: [neovim]

